node() {
    try {
        String ANSI_GREEN = "\u001B[32m"
        String ANSI_NORMAL = "\u001B[0m"
        String ANSI_BOLD = "\u001B[1m"
        String ANSI_RED = "\u001B[31m"
        String ANSI_YELLOW = "\u001B[33m"

        stage('checkout public repo') {
            cleanWs()
            checkout scm
        }

        ansiColor('xterm') {
            stage('deploy'){
                sh "deploy/post-install-script.sh ${params.proto} ${params.domain_name} ${params.core_vault_sunbird_api_auth_token} ${params.private_ingressgateway_ip} ${params.learningservice_ip} ${params.core_vault_sunbird_sso_client_secret} ${params.core_vault_sunbird_google_captcha_site_key_portal} ${params.sunbird_azure_public_storage_account_name} ${params.cassandra} ${params.knowledge_platform_tag}"
                currentBuild.result = 'SUCCESS'
                currentBuild.description = "Private: ${params.private_branch}, Public: ${params.branch_or_tag}"
            }
        }
    }
    catch (err) {
        currentBuild.result = 'FAILURE'
        throw err
    }
}
