{
 "title": "EP Pipeline Metrics",
 "tags": [
  "pipeline",
  "home"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "ntpstaging" }
  ]
 },
 "panels": [
  {
   "title": "Telemetry validation success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry validation failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Dedup failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'DeDuplication' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Events",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'DeDuplication' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"pipeline_metrics\" WHERE \"env\" = 'ntpprod' AND \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Converter Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"autogen\".\"pipeline_metrics\" WHERE \"env\" =~ /^$env$/ AND \"job_name\" = 'TelemetryConverter' AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Converter Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryConverter" }
     ]
    }
   ]
  },
  {
   "title": "DeDuplication Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "DeDuplication Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "ReverseSearch Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "ReverseSearch" }
     ]
    }
   ]
  },
  {
   "title": "ReverseSearch Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "ReverseSearch" }
     ]
    }
   ]
  },
  {
   "title": "ObjectDeNormalization Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "ObjectDeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "ObjectDeNormalization Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "ObjectDeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Public Exhaust De Duplication Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PublicExhaustDeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Public Exhaust De Duplication Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PublicExhaustDeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Private Exhaust De Duplication Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PrivateExhaustDeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Private Exhaust De Duplication Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PrivateExhaustDeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Partner Data Router Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PartnerDataRouter" }
     ]
    }
   ]
  },
  {
   "title": "Partner Data Router Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PartnerDataRouter" }
     ]
    }
   ]
  },
  {
   "title": "Public Telemetry Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PublicTelemetryTask" }
     ]
    }
   ]
  },
  {
   "title": "Public Telemetry Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "PublicTelemetryTask" }
     ]
    }
   ]
  },
  {
   "title": "ES Router Primary Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsRouterPrimary" }
     ]
    }
   ]
  },
  {
   "title": "ES Router Primary Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsRouterPrimary" }
     ]
    }
   ]
  },
  {
   "title": "ES Router Secondary Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsRouterSecondary" }
     ]
    }
   ]
  },
  {
   "title": "ES Router Secondary Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsRouterSecondary" }
     ]
    }
   ]
  },
  {
   "title": "ES Indexer Primary Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsIndexerPrimary" }
     ]
    }
   ]
  },
  {
   "title": "ES Indexer Primary Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsIndexerSecondary" }
     ]
    }
   ]
  },
  {
   "title": "ES Indexer Secondary Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsIndexerSecondary" }
     ]
    }
   ]
  },
  {
   "title": "ES Indexer Secondary Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "EsIndexerSecondary" }
     ]
    }
   ]
  },
  {
   "title": "Processed message For Device Location Updater",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"processed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater' AND \"env\" = 'ntpprod') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "ntpprod" }
     ]
    }
   ]
  },
  {
   "title": "Cassandra DB error for Telemetry Location Updater",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"db_error\") FROM \"pipeline_metrics\" WHERE (\"env\" = 'ntpprod' AND \"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "db_error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "ntpprod" }
     ]
    }
   ]
  },
  {
   "title": "cache empty values for device location",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "cache_empty_values" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=", "value": "ntpprod" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  }
 ]
}