{
 "title": "Secor Consumer Lag and kafka topics details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "ntpstaging" }
  ]
 },
 "panels": [
  {
   "title": "Topics partition count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=~\"$env.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics current offset",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=~\"$env.*\"}",
     "legendFormat": "{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.ingestion.backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.ingestion.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.channel.backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.channel.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.raw.backup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.raw.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.failed.backup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.failed.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.learning.failed.events.backup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.learning.failed.events.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.denorm.backup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.denorm.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.unique.backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.unique.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.graph.events.backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.graph.events.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.pipeline_metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.pipeline.metrics\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.derived.backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.derived.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  }
 ]
}