def writeBlock(File file, String module, String jobname, String tag){
    file.append("                \"Building " + jobname + "\": {\n")
    file.append("                    " + jobname + "Result =  build(job: '" + module + "/" + jobname + "', parameters: [string(name: 'github_release_tag', value: '" + tag + "')], propagate: false).result\n")
    file.append("                    echo  \"" + jobname + " build status = \"+ " + jobname + "Result\n")
    file.append("                    sh \"echo " + jobname + " job status = \$" + jobname + "Result >> out.txt\"\n")
}

def continueBlock(File file){
    file.append("                },\n")
}

def closeBlock(File file){
    file.append("                }\n")
}

def newBlock(File file){
    file.append("        )\n")
    file.append("        parallel(\n")
}

node(){
    sh "rm -rf out.txt"
    repoList = params.repos
    repoList = repoList.replaceAll('\t', ' ')
    repoList = repoList.replaceAll("(?m)^\\s*\$[\n\r]{1,}", "")
    File file = new File("/var/lib/jenkins/Jenkinsfile.master.build")
    repoListSorted = repoList.split('\n').sort()
    file.write("node() {\n    stage('Building generated Jenkinsfile') {\n" +  "        parallel(\n")
    listLength = repoListSorted.length - 1
    storedSeq = 0
    next = nextSeq = null

    for (i= 0; i < listLength; i++){
        if (i == 0)
            continue
        line = repoListSorted[i]
        if(i+1 < listLength) {
            next = repoListSorted[i + 1]
            nextSeq = next.split(' ')[0]
        }
        else
            next = nextSeq = "EOF"

        seq = line.split(' ')[0]
        module = line.split(' ')[1]
        jobname = line.split(' ')[2]
        tag = line.split(' ')[3]

        if(seq == nextSeq) {
            writeBlock(file, module, jobname, tag)
            continueBlock(file)
        }
        else if (seq != nextSeq && nextSeq != "EOF") {
            writeBlock(file, module, jobname, tag)
            closeBlock(file)
            newBlock(file)
        }
        else if(nextSeq == "EOF")
            writeBlock(file, module, jobname, tag)
    }
    file.append("                }\n")
    file.append("        )\n")
file.append("    sh \"echo ============================================\"\n    sh \"cat out.txt\"\n    sh \"echo ============================================\"\n")

    file.append("    }\n}")
    load '/var/lib/jenkins/Jenkinsfile.master.build'
}
