@Library('deploy-conf') _
node() {
    try {
        String ANSI_GREEN = "\u001B[32m"
        String ANSI_NORMAL = "\u001B[0m"
        String ANSI_BOLD = "\u001B[1m"
        String ANSI_RED = "\u001B[31m"
        String ANSI_YELLOW = "\u001B[33m"

        stage('checkout public repo') {
            folder = new File("$WORKSPACE/.git")
            if (folder.exists())
            {
               println "Found .git folder. Clearing it.."
               sh'git clean -fxd'
            }
            checkout scm
        }

            ansiColor('xterm') {
                values = lp_dp_params()
                values.put('module', 'Core')
                stage('get artifact') {
                    currentWs = sh(returnStdout: true, script: 'pwd').trim()
                    artifact = values.artifact_name + ":" + values.artifact_version
                    values.put('currentWs', currentWs)
                    values.put('artifact', artifact)
                    artifact_download(values)
                }
                stage('deploy artifact'){
                    sh """
                       unzip ${artifact}
                       unzip -o collection-editor.zip -d collection-editor
                       mv collection-editor ansible
                    """
                    
                    sh """
                       cd ansible/collection-editor
                       npm config set strict-ssl false
                       npm install
                       npm install promise
                       gulp minifyJs # To rename the minified files
                       gulp copystyleImages
                       gulp clean
                       gulp injectrenamedfiles  # Inject the minified files to index.html
                       gulp package # Package the build
                    """  
                    sh """
                      mkdir iframe
                      unzip ansible/collection-editor/dist/editor/collection-editor-iframe-latest.zip -d iframe/
                    """

                    ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                    ansibleExtraArgs = "--tags collection-editor --extra-vars \"folder_name=collection-editor source_name=${currentWs}/iframe\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                    values.put('ansiblePlaybook', ansiblePlaybook)
                    values.put('ansibleExtraArgs', ansibleExtraArgs)
                    println values
                    ansible_playbook_run(values)

                    ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                    ansibleExtraArgs = "--tags editor --extra-vars \"folder_name=artefacts/editor source_name=${currentWs}/ansible/collection-editor/dist/editor\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                    values.put('ansiblePlaybook', ansiblePlaybook)
                    values.put('ansibleExtraArgs', ansibleExtraArgs)
                    println values
                    ansible_playbook_run(values)
                    ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                    ansibleExtraArgs = "--tags core-plugins --extra-vars \"folder_name=artefacts/coreplugins source_name=${currentWs}/ansible/collection-editor/dist/coreplugins\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                    values.put('ansiblePlaybook', ansiblePlaybook)
                    values.put('ansibleExtraArgs', ansibleExtraArgs)
                    println values
                    ansible_playbook_run(values)
                    currentBuild.result = 'SUCCESS'
                    archiveArtifacts artifacts: "${artifact}", fingerprint: true, onlyIfSuccessful: true
                    archiveArtifacts artifacts: 'metadata.json', onlyIfSuccessful: true
                    currentBuild.description = "Artifact: ${values.artifact_version}, Private: ${params.private_branch}, Public: ${params.branch_or_tag}"
                }
            }
            summary()
     }
    catch (err) {
        currentBuild.result = 'FAILURE'
        throw err
    }    
    finally {
        slack_notify(currentBuild.result)
        email_notify()
    }
}
