#!groovy

node('docker') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }

       stage('Pre-Build'){

         sh('./pipelines/monitor/installDeps.sh')

       }

       stage('Deploy to Dev'){

         sh 'TARGET_ENV=dev ./pipelines/monitor/deploy.sh'

       }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
