#!groovy

node('docker') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }

       stage('Pre-Build'){

         sh('./pipelines/sunbird/installDeps.sh')

       }

       stage('Deploy to Dev'){

         sh './pipelines/sunbird/deploy.sh'

       }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
