source 'https://rubygems.org'
gem 'jekyll-gist', '1.1.0'
gem 'jekyll', '2.5.3'
gem 'rdiscount'
gem 'kramdown'
gem 'sass'
gem 'nokogiri'
gem 's3_website'
gem 'html-proofer'
gem 'faraday'
gem 'jekyll-redirect-from'
