FROM sunbird/offline-installer:release-2.1
MAINTAINER "S M Y ALTAMASH" "<smy.altamash@gamil.com>"
ARG GITHUB_ACCESS_TOKEN={{offline_git_access_token}}
ARG GITHUB_PRIVATE_REPO={{offline_git_private_repo}}
ARG TARGET_ENVIRONMENT={{offline_target_env}}
WORKDIR /private/
ADD . /private/
WORKDIR /private/src/
CMD npm install && npm run dist
CMD npm run dist-win64
CMD npm run dist-linux
