@Library('deploy-conf') _
node() {
    try {
        stage('checkout public repo') {
            cleanWs()
            checkout scm
        }

        stage('define variables') {
            def values = docker_params()
            if(values == "first run"){
               currentBuild.result = 'SUCCESS'
               return
             }
            currentWs = sh(returnStdout: true, script: 'pwd').trim()
            ansiblePlaybook = "$currentWs/ansible/deploy.yml"
            ansibleExtraArgs = """\
                               --tags "stack-sunbird" --extra-vars "hub_org=$hub_org image_name=$values.image_name
                               image_tag=$values.image_tag service_name=content-service
                               deploy_content=True" --vault-password-file /home/ops/vault
                               """.stripIndent().replace("\n"," ")
            values.put('currentWs', currentWs)
            values.put('ansiblePlaybook', ansiblePlaybook)
            values.put('ansibleExtraArgs', ansibleExtraArgs)
            ansible_playbook_run(values)
            archiveArtifacts 'metadata.json'
        }
    }
    catch (err) {
        throw err
    }
}
