FROM ubuntu:16.04
MAINTAINER Lakhan Mandloi <lakhan_m@tekditechnologies.com>

USER root
# Update everything
RUN apt update && \
    apt install -y build-essential \
        zlib1g-dev \
        git \
        locales \
        curl \
        ruby-full && \
    curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt install -y nodejs

RUN gem install bundle \
        liquid-rails \
        documentation \
        branch_io \
        rubygems-update && \
    gem update --system 

RUN locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    export LANGUAGE=en_US:en && \
    export LC_ALL=en_US.UTF-8
