{
 "title": "API Manager Beta",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code=~\"2..|3..\", status_code!= \"total\"}[1m])) by (api, status_code) / sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m])) by (api, status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code!~\"2..|3..|total\"}[1m])) by (api, status_code) / sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m])) by (api, status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Average Total Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_latency_time_sum{api=~\"${api}\"}[1m]) / rate(kong_latency_time_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Average Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_upstream_latency_time_sum{api=~\"${api}\"}[1m])) by (api)  / sum(rate(kong_upstream_latency_time_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Total Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p99-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p95-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p90-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p50-{{api}}"
    }
   ]
  },
  {
   "title": "Upstream Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p99-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p95-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p90-{{api}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p50-{{api}}"
    }
   ]
  },
  {
   "title": "Requests per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_count{api =~ \"$api\"}[$interval])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_size_sum{api=~\"${api}\"}[1m]) / rate(kong_request_size_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "avg-{{api}}"
    },
    {
     "expr": "sum(rate(kong_request_size_sum{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "total-{{api}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_response_size_sum{api=~\"${api}\"}[1m]) / rate(kong_response_size_sum{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "avg-{{api}}"
    },
    {
     "expr": "sum(rate(kong_response_size_sum{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "total-{{api}}"
    }
   ]
  },
  {
   "title": "Apdex Score (Threshold of 500ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_latency_time_bucket{api=~\"${api}\", le=\"0.5\"}[1m])) by (api) / sum(rate(kong_latency_time_count[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}