{
 "title": "API Manager Request/Response Size Aggregated Beta",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kong_request_count, sb_cluster)"
   },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   },
   {
    "name": "requestSize",
    "label": "Request size in kB",
    "query": "label_values(kong_request_size_bucket,le)"
   },
   {
    "name": "responseSize",
    "label": "Response size in kB",
    "query": "label_values(kong_response_size_bucket,le)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "repeat": "requestSize",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[5m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[5m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Responses under Size $responseSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "repeat": "responseSize",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$responseSize\"}[5m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$responseSize\"}[5m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Map - Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "api",
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[5m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[5m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Map - Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "api",
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[5m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[5m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}