{
 "title": "API Manager",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "swarm",
    "query": "label_values(kong_request_count, cluster)"
   },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{cluster=~\"$swarm\", api=~\"${api}\"}[5m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kong_latency_time{cluster=~\"$swarm\", api=~\"${api}\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kong_upstream_latency_time{cluster=~\"$swarm\", api=~\"${api}\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(kong_request_status_count{cluster=~\"$swarm\", api=~\"${api}\",status_code=~\"2..|3..\"}[5m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count{cluster=~\"$swarm\", api=~\"${api}\"}[5m]))) by (api,status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(kong_request_status_count{cluster=~\"$swarm\", api=~\"${api}\",status_code!~\"2..|3..\"}[5m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count{cluster=~\"$swarm\", api=~\"${api}\"}[5m]))) by(api,status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kong_request_size{cluster=~\"$swarm\", api=~\"${api}\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kong_response_size{cluster=~\"$swarm\", api=~\"${api}\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } }
 ]
}