{
 "title": "API Manager Request/Response Size Aggregated",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kong_request_count, sb_cluster)"
   },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   },
   {
    "name": "requestSize",
    "label": "Request size in kB",
    "query": "label_values(kong_request_size_bucket,le)"
   },
   {
    "name": "responseSize",
    "label": "Response size in kB",
    "query": "label_values(kong_response_size_bucket,le)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "repeat": "requestSize",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Number of Requests under Size $requestSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$requestSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Responses under Size $responseSize kB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "repeat": "responseSize",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api=~\"${api}\", le=~\"$responseSize\"}[1m])) by (api,sb_cluster)",
       "legendFormat": "{{api}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\", le=~\"$responseSize\"}[1m])) by (api)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Map - Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "api",
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}-{{sb_cluster}}"
      },
      {
       "expr": "sum(increase(kong_request_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api = \"$api\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Map - Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "api",
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Heat Map of all Buckets - $api ($cluster)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=\"$cluster\", api = \"$api\"}[1m])) by (le,api,sb_cluster)",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "sum(increase(kong_response_size_bucket{sb_cluster=~\"$cluster\", sb_cluster!=\"$cluster\", api=~\"${api}\"}[1m])) by (le,api)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}