{
 "title": "Dashboard-All",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffic : Requests / Sec (both Swarm3 and K8s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[2m]))",
     "legendFormat": "Today"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1d))  ",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m] offset 1w))  ",
     "legendFormat": "Last Week Same Day"
    }
   ]
  },
  {
   "title": "status count by percentage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total[${__range_s}s])) by (status)",
     "legendFormat": "count"
    },
    {
     "expr": "sum(increase(nginx_http_requests_total[${__range_s}s])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[${__range_s}s])) * 100"
    },
    {
     "expr": "sum(increase(nginx_http_requests_total[${__range_s}s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Traffic : Requests / Sec - Swarm-3",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Traffic : Requests / Sec - Kubernetes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "4xx Error % Swarm",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|5..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "4xx Error % Kubernetes-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|5..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Error % Swarm3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Error % kubernetes-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[1m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Load avg on VM's",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk utilization %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{ mountpoint=\"/\", job=~\".*node-exporter\"} - node_filesystem_free_bytes{ mountpoint=\"/\"}) * 100 / node_filesystem_size_bytes{mountpoint=\"/\"}  * on (instance) group_left(nodename) node_uname_info )  by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Kafka servers Data Disk utilization % ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{ mountpoint=\"/data\", job=~\".*node-exporter\"} - node_filesystem_free_bytes{ mountpoint=\"/data\"}) * 100 / node_filesystem_size_bytes{mountpoint=\"/data\"}  * on (instance) group_left(nodename) node_uname_info )  by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}