{
 "title": "Data Pipeline Metrics Flink",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ingest Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion Router lag",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"ingest-router-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "IngestRouter lag",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"ingest-router-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "TelemetryExtractor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Extractor Success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_TelemetryExtractorJob_success_batch_count[$__range]))"
      }
     ]
    },
    {
     "title": "Extractor Duplicates",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_TelemetryExtractorJob_duplicate_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Raw Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_TelemetryExtractorJob_success_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Extractor Failed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_TelemetryExtractorJob_failed_batch_count[$__range]))"
      }
     ]
    },
    {
     "title": "Telemetry Extractor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_TelemetryExtractorJob_success_event_count)",
       "legendFormat": "ExtractorSuccess"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_TelemetryExtractorJob_duplicate_event_count)",
       "legendFormat": "ExtractorDuplicates"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_TelemetryExtractorJob_failed_batch_count)",
       "legendFormat": "ExtractorFailed"
      }
     ]
    },
    {
     "title": "TelemetryExtractor lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"telemetry-extractor-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline Preprocessor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_success_event_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_failed_event_count[$__range])) "
      }
     ]
    },
    {
     "title": "Unique Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_unique_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Duplicate Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_duplicate_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Invalid Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_failed_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Invalid Events %",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_failed_event_count[$__range])) / (sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_failed_event_count[$__range])) +sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_validation_success_event_count[$__range]))) * 100"
      }
     ]
    },
    {
     "title": "Primary Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_primary_route_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_share_item_event_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Audit Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_audit_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_log_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Share Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_share_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Error Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_error_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Pipeline Preprocessor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_primary_route_success_count)",
       "legendFormat": "Primary Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_log_route_success_count)",
       "legendFormat": "Log Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_error_route_success_count)",
       "legendFormat": "Error Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_PipelinePreprocessorJob_audit_route_success_count)",
       "legendFormat": "Audit Events"
      }
     ]
    },
    {
     "title": "Preprocessor lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"pipeline-preprocessor-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "DenormalizationPrimary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_device_cache_hit{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "User meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_user_cache_hit{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Dialcode meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_dialcode_cache_hit{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Content meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_content_cache_hit{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Location meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_loc_cache_hit{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Expired Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_events_expired{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))",
       "legendFormat": "Expired events"
      }
     ]
    },
    {
     "title": "Device meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_device_cache_miss{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "User meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_user_cache_miss{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Dialcode meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_dialcode_cache_miss{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Content meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_content_cache_miss{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Location meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_loc_cache_miss{job=\"de-normalization-primary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "DenormalizationPrimary",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DenormalizationJob_loc_total{job=\"de-normalization-primary-taskmanager-prometheus\"})",
       "legendFormat": "Denorm success"
      }
     ]
    },
    {
     "title": "DenormalizationPrimary lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"de-normalization-primary-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "DenormalizationSecondary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_device_cache_hit{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "User meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_user_cache_hit{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Dialcode meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_dialcode_cache_hit{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Content meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_content_cache_hit{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Location meta success",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_loc_cache_hit{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Expired Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_events_expired{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))",
       "legendFormat": "Expired events"
      }
     ]
    },
    {
     "title": "Device meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_device_cache_miss{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "User meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_user_cache_miss{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Dialcode meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_dialcode_cache_miss{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Content meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_content_cache_miss{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Location meta miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DenormalizationJob_loc_cache_miss{job=\"de-normalization-secondary-taskmanager-prometheus\"}[$__range]))"
      }
     ]
    },
    {
     "title": "DenormalizationSecondary",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DenormalizationJob_loc_total{job=\"de-normalization-secondary-taskmanager-prometheus\"})",
       "legendFormat": "Denorm success"
      }
     ]
    },
    {
     "title": "DenormalizationSecondarylag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"de-normalization-secondary-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Telemetry Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DruidValidatorJob_telemetry_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Summary Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DruidValidatorJob_summary_route_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Validation Failed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DruidValidatorJob_validation_failed_message_count[$__range]))"
      }
     ]
    },
    {
     "title": "Duplicate Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_DruidValidatorJob_duplicate_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Druid Validator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DruidValidatorJob_telemetry_route_success_count)",
       "legendFormat": "Telemetry Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DruidValidatorJob_summary_route_success_count)",
       "legendFormat": "Summary Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DruidValidatorJob_validation_failed_message_count)",
       "legendFormat": "Validation failed"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DruidValidatorJob_duplicate_event_count)",
       "legendFormat": "Duplicate Events"
      }
     ]
    },
    {
     "title": "DruidValidator lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"druid-validator-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "SummaryDenorm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SummaryDenorm ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_content_cache_hit)",
       "legendFormat": "ContentCacheHit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_content_cache_miss)",
       "legendFormat": "ContentCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_content_total)",
       "legendFormat": "ContentTotal"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_device_cache_hit)",
       "legendFormat": "DeviceCacheHit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_device_cache_miss)",
       "legendFormat": "DeviceCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_device_total)",
       "legendFormat": "DeviceTotal"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_dialcode_cache_hit)",
       "legendFormat": "DialcodeCacheHit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_dialcode_cache_miss)",
       "legendFormat": "DialcodeCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_dialcode_total)",
       "legendFormat": "DialcodeCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_user_cache_hit)",
       "legendFormat": "UserCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_events_expired)",
       "legendFormat": "ExpiredEvent"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_unique_event_count)",
       "legendFormat": "UniqueEventCount"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_user_cache_hit)",
       "legendFormat": "UserCacheHit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_user_cache_miss)",
       "legendFormat": "UserCacheMiss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_SummaryDenormalizationJob_user_total)",
       "legendFormat": "UserTotal"
      }
     ]
    },
    {
     "title": "SummaryDenorm lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max{ job = \"summary-denormalization-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "UserCacheUpdaterV2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "User-Cache-Updater-v2",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_UserCacheUpdaterJobV2_success_message_count)",
       "legendFormat": "User-Cache-Updater-Success"
      }
     ]
    },
    {
     "title": "User-Cache-Updater-v2 lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"user-cache-updater-v2-taskmanager-prometheus\" })",
       "legendFormat": "User-Cache-Updater-lag"
      }
     ]
    }
   ]
  },
  {
   "title": "DeviceProfileUpdater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "DeviceProfileUpdater",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DeviceProfileUpdaterJob_success_event_count)",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DeviceProfileUpdaterJob_device_db_update_count)",
       "legendFormat": "DbUpdate"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DeviceProfileUpdaterJob_failed_event_count)",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_DeviceProfileUpdaterJob_device_cache_update_count)",
       "legendFormat": "CacheUpdate"
      }
     ]
    },
    {
     "title": "DeviceProfileUpdater lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"device-profile-updater-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "ContentCacheUpdater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContentCacheUpdater",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_ContentCacheUpdaterJob_cache_hit_count)",
       "legendFormat": "Cache Hit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_ContentCacheUpdaterJob_dial_codes_api_hit_count)",
       "legendFormat": "DialCode Api Hit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_ContentCacheUpdaterJob_dial_codes_api_miss_count)",
       "legendFormat": "DialCode Api Miss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_ContentCacheUpdaterJob_dial_codes_cache_hit_count)",
       "legendFormat": "DialCode Cache Hit"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_ContentCacheUpdaterJob_total_dial_code_count)",
       "legendFormat": "Total DialCode"
      }
     ]
    },
    {
     "title": "ContentCacheUpdater lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"content-cache-updater-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  }
 ]
}