{
 "title": "Device Register API Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Calls",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"api_calls\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter",
     "select": [
      [
       { "params": [ "api_calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  },
  {
   "title": "[Postgres] Location DB Success",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"location_db_hit\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter",
     "select": [
      [
       { "params": [ "location_db_success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  },
  {
   "title": "[Postgres] Location DB miss",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"location_db_miss\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter",
     "select": [
      [
       { "params": [ "location_db_miss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  },
  {
   "title": "[Postgres] Location DB Error",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"location_db_error\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter",
     "select": [
      [
       { "params": [ "location_db_error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  },
  {
   "title": "[Cassandra] Device DB Success",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"device_db_save_success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter ",
     "select": [
      [
       { "params": [ "device_db_save_success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  },
  {
   "title": "[Cassandra] Device DB Error",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"device_db_save_error\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeviceRegisterAPI') AND $timeFilter",
     "select": [
      [
       { "params": [ "device_db_save_error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeviceRegisterAPI" }
     ]
    }
   ]
  }
 ]
}