{
 "title": "DP Jobs Consumer lag",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Telemetry Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Location Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Denormalization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter ",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Druid Events Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter ",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "Events Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "EventsRouter" }
     ]
    }
   ]
  },
  {
   "title": "Redis Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "redis-updater" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT consumer_lag FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "consumer_lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  }
 ]
}