{
 "title": "DP-Jobs-Consumer-lag-prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Assessment Aggregator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"AssessmentAggregator\"})"
    }
   ]
  },
  {
   "title": "Deduplication",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"DeDuplication\"})"
    }
   ]
  },
  {
   "title": "Denormalization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"DeNormalization\"})"
    }
   ]
  },
  {
   "title": "Derived DeDuplication",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"DerivedDeDuplication\"})"
    }
   ]
  },
  {
   "title": "Device ProfileUpdater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"DeviceProfileUpdater\"})"
    }
   ]
  },
  {
   "title": "Druid Events Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"DruidEventsValidator\"})"
    }
   ]
  },
  {
   "title": "Events Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"EventsRouter\"})"
    }
   ]
  },
  {
   "title": "Telemetry Extractor",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"TelemetryExtractor\"})"
    }
   ]
  },
  {
   "title": "Telemetry Location Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"TelemetryLocationUpdater\"})"
    }
   ]
  },
  {
   "title": "Telemetry Redacter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"TelemetryRedacter\"})"
    }
   ]
  },
  {
   "title": "Telemetry Router",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"TelemetryRouter\"})"
    }
   ]
  },
  {
   "title": "Telemetry Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"TelemetryValidator\"})"
    }
   ]
  },
  {
   "title": "UserCache Updater",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(samza_pipeline_metrics_consumer_lag{job_name= \"UserCacheUpdater\"})"
    }
   ]
  }
 ]
}