{
 "title": "DP Percentage Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Extractor Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"batch-success\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extractor Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"batch-error\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extractor Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extractor Duplicate Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"duplicate\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extractor Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\") + sum(\"error\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Validator Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "De Duplication Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "De Duplication Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "De Duplication Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "De Duplication Duplicate Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"duplicate\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "De Duplication Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT (sum(\"primary-route-success\") + sum(\"secondary-route-success\")) / (sum(\"error\") + sum(\"primary-route-success\") + sum(\"secondary-route-success\") + sum(\"skipped\") + sum(\"failed\") ) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "primary-route-success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"primary-route-success\") + sum(\"secondary-route-success\") + sum(\"skipped\") + sum(\"failed\") ) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"primary-route-success\") + sum(\"secondary-route-success\") + sum(\"skipped\") + sum(\"failed\") ) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Router Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"primary-route-success\") + sum(\"secondary-route-success\") + sum(\"skipped\") + sum(\"failed\") ) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location Updater Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location Updater Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location Updater Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location Updater Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DeNormalization Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DeNormalization Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DeNormalization Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DeNormalization Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Druid Validator Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Druid Validator Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Druid Validator Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Druid Validator Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Router Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Router Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Router Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Router Duplicate Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"duplicate\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events Router Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Derived DeDuplication Success Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DerivedDeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Derived DeDuplication Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DerivedDeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Derived DeDuplication Skipped Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"skipped\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DerivedDeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Derived DeDuplication Duplicate Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"duplicate\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DerivedDeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Derived DeDuplication Error Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\") + sum(\"failed\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DerivedDeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}