{
 "title": "ED Infra Status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "nodename",
    "query": "label_values(node_uname_info{job=~\".*node-exporter\"},nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods UP",
   "type": "table",
   "gridPos": { "h": 22, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 1,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_deployment_status_replicas{namespace=\"$namespace\"} !=0",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Pods DOWN",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"$namespace\"} == 0\n"
    }
   ]
  },
  {
   "title": "Backend VMs health",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 9, "y": 10 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "POD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Load avg on VM's",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\", nodename=~\"$nodename\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}