{
 "title": "Envoy Proxy",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(envoy_cluster_upstream_cx_total, envoy_cluster_name)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\", job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "2xx Success %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"3..|4..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
     "legendFormat": "{{job}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "5xx Failures %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|3..|4..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, instance, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, instance)",
     "legendFormat": "{{job}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "3xx Success %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|4..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
     "legendFormat": "{{job}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "4xx Failures %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|3..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
     "legendFormat": "{{job}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[$__range])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Upstream Connections and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le,job))",
       "legendFormat": "{{job}} - 50th %ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le, job))",
       "legendFormat": "{{job}} - 95th %ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le,job))",
       "legendFormat": "{{job}} - 99th %ile"
      }
     ]
    },
    {
     "title": "Upstream Request Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - connect timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - pending failure ejection"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - pending overflow"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - per try request timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request reset"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - destroy initialized from originating service"
      },
      {
       "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - destroy initialized from remote service"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request failed maintenance mode"
      }
     ]
    },
    {
     "title": "Upstream Total active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Upstream members",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job) / count(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - healthy"
      },
      {
       "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job) / count(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - total"
      }
     ]
    },
    {
     "title": "Upstream Network Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in"
      },
      {
       "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream Connections and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream Total active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} - ingress_http"
      },
      {
       "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} - admin"
      }
     ]
    },
    {
     "title": "Downstream Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in (ingress_http)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out (ingress_http)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in (admin)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out (admin)"
      }
     ]
    },
    {
     "title": "Downstream Total active requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - ingress_http"
      },
      {
       "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - admin"
      }
     ]
    }
   ]
  }
 ]
}