{
 "title": "Envoy Global",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Live servers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_health_check_attempt[1m]))",
     "legendFormat": "Global HC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  }
 ]
}