{
 "title": "EP Pipeline Metrics",
 "tags": [
  "pipeline",
  "home"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "ntpprod" }
  ]
 },
 "panels": [
  {
   "title": "Extractor success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"batch-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "Extractor failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"batch-error\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "batch-error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "Extractor Duplicates",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "duplicate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "Extractor failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"batch-error\") / (sum(\"batch-success\") + sum(\"batch-error\") + sum(\"skipped\") + sum(\"duplicate\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryExtractor') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater Failed Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"error\") / (sum(\"error\") + sum(\"success\")) * 100 FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryExtractor" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouterSecondary success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"secondary-route-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"job_name\" = 'DeDuplication' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry validation failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TelemetryRaw events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") + sum(\"failed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Duplicate events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"duplicate\") FROM \"pipeline_metrics\" WHERE  \"job_name\" = 'DeDuplication' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation skipped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"skipped\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Denorm expired events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"expired_event\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "expired_event" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouterPrimary success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"primary-route-success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "DruidRouter success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "DruidRouter duplicates",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"duplicate\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pipeline_metrics",
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"autogen\".\"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"error\", \"failed\" FROM \"autogen\".\"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryValidator lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE \"job_name\" = 'TelemetryValidator' AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryValidator" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"duplicate\", \"error\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'DeDuplication') AND $timeFilter",
     "select": [
      [
       { "params": [ "duplicate" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE \"job_name\" = 'DeDuplication' AND $timeFilter",
     "select": [
      [
       { "params": [ "duplicate" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeDuplication" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouter Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouter failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"error\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "TelemetryRouter lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryRouter" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"failed\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "LocationUpdater lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'TelemetryLocationUpdater') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "TelemetryLocationUpdater" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\", \"skipped\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation expired",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"expired_event\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "expired_event" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "Denormalisation lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\", \"skipped\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DeNormalization') AND $timeFilter",
     "select": [
      [
       { "params": [ "expired_event" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DeNormalization" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"failed\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "DruidValidator lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'DruidEventsValidator') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "EventsRouter Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"success\" FROM \"pipeline_metrics\" WHERE ( \"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "EventsRouter failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"failed\", \"duplicate\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  },
  {
   "title": "EventsRouter lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"consumer_lag\" FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'EventsRouter') AND $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DruidEventsValidator" }
     ]
    }
   ]
  }
 ]
}