{
 "title": "Exhaust Reports Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Progress Exhaust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time (dataproduct_progressexhaustjob_total_requests[1h])"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time (dataproduct_progressexhaustjob_success_requests[1h])"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time (dataproduct_progressexhaustjob_failed_requests[1h])"
    }
   ]
  },
  {
   "title": "Duplicate Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_progressexhaustjob_duplicate_requests[1h])"
    }
   ]
  },
  {
   "title": "Time Taken in Hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time (dataproduct_progressexhaustjob_time_taken_secs[1h])"
    }
   ]
  },
  { "title": "Userinfo Exhaust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_userinfoexhaustjob_total_requests[1h])"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_userinfoexhaustjob_success_requests[1h])"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_userinfoexhaustjob_failed_requests[1h])"
    }
   ]
  },
  {
   "title": "Duplicate Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_userinfoexhaustjob_duplicate_requests[1h])"
    }
   ]
  },
  {
   "title": "Time Taken in Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_userinfoexhaustjob_time_taken_secs[1h])"
    }
   ]
  },
  { "title": "Response Exhaust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_responseexhaustjob_total_requests[1h])"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_responseexhaustjob_success_requests[1h])"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_responseexhaustjob_failed_requests[1h])"
    }
   ]
  },
  {
   "title": "Duplicate Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_responseexhaustjob_duplicate_requests[1h])"
    }
   ]
  },
  {
   "title": "Time Taken in secs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dataproduct_responseexhaustjob_time_taken_secs[1h])"
    }
   ]
  }
 ]
}