{
 "title": "Graylog Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=~\"graylog\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Instant Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Buffer Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gl_buffer_size{instance=~\"$instance\", type=\"input\"}"
    }
   ]
  },
  {
   "title": "Input Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{instance=~\"$instance\", type=\"input\"} / gl_buffer_size{instance=~\"$instance\", type=\"input\"}) * 100"
    }
   ]
  },
  {
   "title": "Process Buffer Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gl_buffer_size{instance=~\"$instance\", type=\"process\"}"
    }
   ]
  },
  {
   "title": "Process Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{instance=~\"$instance\", type=\"process\"} / gl_buffer_size{instance=~\"$instance\", type=\"process\"}) * 100"
    }
   ]
  },
  {
   "title": "Output Buffer Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gl_buffer_size{instance=~\"$instance\", type=\"output\"}"
    }
   ]
  },
  {
   "title": "Output Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{instance=~\"$instance\", type=\"output\"} / gl_buffer_size{instance=~\"$instance\", type=\"output\"}) * 100"
    }
   ]
  },
  {
   "title": "Journal Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gl_journal_size_limit{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Journal Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(gl_journal_size{instance=~\"$instance\"} / gl_journal_size_limit{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  { "title": "Journal Utilization / Backlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Journal Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "gl_journal_utilization_ratio{instance=~\"$instance\"}",
     "legendFormat": "Journal Utilization"
    }
   ]
  },
  {
   "title": "Journal Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_journal_entries_uncommitted{instance=~\"$instance\"}",
     "legendFormat": "Journal Backlog"
    }
   ]
  },
  { "title": "Journal Read / Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Journal Read Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_journal_read_1_sec_rate{instance=~\"$instance\"}",
     "legendFormat": "Journal Read"
    }
   ]
  },
  {
   "title": "Journal Write Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_journal_append_1_sec_rate{instance=~\"$instance\"}",
     "legendFormat": "Journal Write"
    }
   ]
  },
  { "title": "Message In / Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Incoming Message Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_input_throughput_1_sec_rate{instance=~\"$instance\"}",
     "legendFormat": "Message In"
    }
   ]
  },
  {
   "title": "Outgoing Message Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gl_output_throughput_1_sec_rate{instance=~\"$instance\"}",
     "legendFormat": "Message Out"
    }
   ]
  }
 ]
}