{
 "title": "Ingestion Kafka cluster Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "ntpprod" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "kafka_brokers" }
     ]
    },
    {
     "title": "ISR Details",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_topic_partition_in_sync_replica{topic!=\"__consumer_offsets\",topic!=\"__samza_*\"}",
       "legendFormat": "{{topic}}::{{partition}}"
      }
     ]
    },
    {
     "title": "Partitions per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(topic) (kafka_topic_partitions{topic=~\"$topic\"})",
       "legendFormat": "{{topic}}::{{partition}}"
      }
     ]
    },
    {
     "title": "Replications per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(topic) (kafka_topic_partition_replicas{topic=~\"$topic\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  { "title": "Secor Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$env.telemetry.ingestion.backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.ingestion.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.events.deviceprofile.backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.events.deviceprofile.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.graph.events.backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.graph.events.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.telemetry.assess",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.assess\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "$env.learning.failed.events.backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.learning.failed.events.backup\"}",
     "legendFormat": "{{consumergroup}}::{{topic}}::{{partition}}"
    }
   ]
  }
 ]
}