{
 "title": "KP Flink Jobs Metrics",
 "tags": [
  "KP",
  "Flink",
  "Metrics",
  "Knowledge Job"
 ],
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "Post Publish Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_skipped_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Batch Creation Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_count[$__range]))"
      }
     ]
    },
    {
     "title": "Batch Creation Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Batch Creation Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "DialCode Link Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_count[$__range]))"
      }
     ]
    },
    {
     "title": "DialCode Link Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "DialCode Link Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "QR Image Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_qr_image_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Shallow Copy Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_post_publish_processor_shallow_copy_count[$__range]))"
      }
     ]
    },
    {
     "title": "Post Publish Processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_skipped_events_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "Post Publish Processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_success_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_success_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_skipped_events_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_batch_creation_failed_count) + sum(flink_taskmanager_job_task_operator_post_publish_processor_dial_link_failed_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    }
   ]
  },
  {
   "title": "QuestionSet Publish",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_skipped_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Question Publish Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_count[$__range]))"
      }
     ]
    },
    {
     "title": "Question Publish Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Question Publish Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "QuestionSet Publish Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_count[$__range]))"
      }
     ]
    },
    {
     "title": "QuestionSet Publish Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "QuestionSet Publish Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "QuestionSet Publish",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_question_publish_success_count) + sum(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_success_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_skipped_event_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_question_publish_failed_count) + sum(flink_taskmanager_job_task_operator_questionset_publish_questionset_publish_failed_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "QuestionSet Publish",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"questionset-publish-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Search Indexer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_skipped_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count[$__range])) +  sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count[$__range])) +  sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Composite Search Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Composite Search Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Composite Search Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dialcode Metrics Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dailcode Metrics Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dailcode Metrics Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dailcode External Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dailcode External Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count[$__range]))"
      }
     ]
    },
    {
     "title": "Dailcode External Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count[$__range]))"
      }
     ]
    },
    {
     "title": "Search Indexer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_success_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_success_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_success_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_skipped_event_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_composite_search_event_failed_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_metric_event_failed_count) + sum(flink_taskmanager_job_task_operator_search_indexer_dialcode_external_event_failed_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_search_indexer_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "Search Indexer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"search-indexer-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Aggregate Updater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Batch Enrolment Update",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_batch_enrolment_update_count[$__range]))"
      }
     ]
    },
    {
     "title": "Retired Collection Skip Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_retired_consumption_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_skipped_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_failed_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Processed Enrolment Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_processed_enrolment_count[$__range]))"
      }
     ]
    },
    {
     "title": "Cache Miss",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_miss_count[$__range]))"
      }
     ]
    },
    {
     "title": "DB Update",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_update_count[$__range]))"
      }
     ]
    },
    {
     "title": "DB Read",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_read_count[$__range]))"
      }
     ]
    },
    {
     "title": "Cache Hit",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_hit_count[$__range]))"
      }
     ]
    },
    {
     "title": "Activity Aggregate Updater",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_failed_events_count)",
       "legendFormat": "ActivityAggregateFailed"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_batch_enrolment_update_count)",
       "legendFormat": "BatchEnolmentUpdate"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_db_update_count)",
       "legendFormat": "DB Update"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_cache_miss_count)",
       "legendFormat": "Cache Miss"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_total_events_count)",
       "legendFormat": "Total Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_activity_aggregate_updater_processed_enrolment_count)",
       "legendFormat": "Processed Enrolments"
      }
     ]
    },
    {
     "title": "ActivityAggUpdater lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"activity-aggregate-updater-taskmanager-prometheus\"})",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Video Stream Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_skipped_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_success_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_failed_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Retried Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_video_stream_generator_retry_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Video Stream Generator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_success_events_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_skipped_events_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_failed_events_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_video_stream_generator_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "Video Stream Generator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"video-stream-generator-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Relation Cache Updater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_skipped_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_success_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Cache Write",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_cache_write_count[$__range]))"
      }
     ]
    },
    {
     "title": "DB Read",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_db_read_count[$__range]))"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_relation_cache_updater_failed_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Relation Cache Updater",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_success_events_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_skipped_event_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_failed_events_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_relation_cache_updater_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "RelationCache Updater lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"relation-cache-updater-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_history_indexer_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_history_indexer_skipped_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_history_indexer_success_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Elasticsearch Failed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_history_indexer_elasticsearch_error_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_history_indexer_failed_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Audit History Indexer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_history_indexer_success_events_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_history_indexer_skipped_events_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_history_indexer_failed_events_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_history_indexer_total_events_count)",
       "legendFormat": "Total Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_history_indexer_elasticsearch_error_events_count)",
       "legendFormat": "ES Failed Events"
      }
     ]
    },
    {
     "title": "Audit History Indexer lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"audit-history-indexer-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Enrolment reconciliation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_total_events_count[$__range]))",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_skipped_events_count[$__range]))",
       "legendFormat": "Skipped Events"
      }
     ]
    },
    {
     "title": "Certificates Issue Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_cert_issue_events_count[$__range]))",
       "legendFormat": "Certificate Issue Count"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_failed_events_count[$__range]))",
       "legendFormat": "Failed Events"
      }
     ]
    },
    {
     "title": "DB Update Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_db_update_count[$__range]))",
       "legendFormat": "DB Update Count"
      }
     ]
    },
    {
     "title": "DB Read Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_db_read_count[$__range]))",
       "legendFormat": "DB Read Count"
      }
     ]
    },
    {
     "title": "Cache Hit Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_cache_hit_count[$__range]))",
       "legendFormat": "Cache Hit Count"
      }
     ]
    },
    {
     "title": "Cache Miss Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_cache_miss_count[$__range]))",
       "legendFormat": "Cache Miss Count"
      }
     ]
    },
    {
     "title": "Retried Consumption Events Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_retired_consumption_events_count[$__range]))",
       "legendFormat": "Retired Consumption Events Count"
      }
     ]
    },
    {
     "title": "Enrolment Complete Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_enrolment_reconciliation_enrolment_complete_count[$__range]))",
       "legendFormat": "Enrolment Complete Count"
      }
     ]
    },
    {
     "title": "Enrolment reconciliation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_enrolment_reconciliation_success_events_count)",
       "legendFormat": "Success Event"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_enrolment_reconciliation_skipped_event_count)",
       "legendFormat": "Skipped Event"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_enrolment_reconciliation_failed_events_count)",
       "legendFormat": "Failed Event"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_enrolment_reconciliation_total_events_count)",
       "legendFormat": "Total Event"
      }
     ]
    },
    {
     "title": "Enrolment reconciliation lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"enrolment-reconciliation-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Asset Enrichment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_skipped_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_success_image_enrichment_event_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_success_video_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Total Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_failed_image_enrichment_event_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_failed_video_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Image Enrichment Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_image_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Image Enrichment Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_success_image_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Image Enrichment Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_failed_image_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Video Enrichment Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 61 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_video_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Video Enrichment Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 61 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_success_video_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Video Enrichment Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 61 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_failed_video_enrichment_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Video Streaming Events",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 65 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_asset_enrichment_video_streaming_event_count[$__range]))"
      }
     ]
    },
    {
     "title": "Asset Enrichment",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_asset_enrichment_success_image_enrichment_event_count) + sum(flink_taskmanager_job_task_operator_asset_enrichment_success_video_enrichment_event_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_asset_enrichment_skipped_event_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_asset_enrichment_failed_image_enrichment_event_count) + sum(flink_taskmanager_job_task_operator_post_publish_failed_video_enrichment_event_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_post_publish_processor_total_events_count)",
       "legendFormat": "Total Events"
      }
     ]
    },
    {
     "title": "Asset Enrichment",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"asset-enrichment-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit event generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_total_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_skipped_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Success Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_success_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Empty props from schema",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_empty_props_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Empty schema for object type",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_empty_schema_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_audit_event_generator_failed_events_count[$__range]))"
      }
     ]
    },
    {
     "title": "Audit Event Generator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_success_events_count)",
       "legendFormat": "Success Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_skipped_events_count)",
       "legendFormat": "Skipped Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_failed_events_count)",
       "legendFormat": "Failed Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_total_events_count)",
       "legendFormat": "Total Events"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_empty_props_events_count)",
       "legendFormat": "Empty props from schema"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_audit_event_generator_empty_schema_events_count)",
       "legendFormat": "Empty schema for object type"
      }
     ]
    },
    {
     "title": "Audit Event Generator lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"audit-event-generator-taskmanager-prometheus\" })",
       "legendFormat": "Consumer lag"
      }
     ]
    }
   ]
  },
  { "title": "Content Publish", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_content_publish_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_content_publish_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Success Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_content_publish_content_publish_success_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_content_publish_content_publish_failed_count[$__range])) + sum(sum_over_time(flink_taskmanager_job_task_operator_content_publish_content_publish_failed_count[$__range]))"
    }
   ]
  },
  {
   "title": "Content Publish",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_content_publish_content_publish_success_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_content_publish_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_content_publish_content_publish_failed_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_content_publish_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Content Publish Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"content-publish-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Collection Cert Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_failed_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Enrolment DB Read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_enrollment_db_read_count[$__range]))"
    }
   ]
  },
  {
   "title": "Enrolment DB Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_db_update_user_enrollment_count[$__range]))"
    }
   ]
  },
  {
   "title": "Course Batch DB Read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_db_course_batch_read_count[$__range]))"
    }
   ]
  },
  {
   "title": "Notification User ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_notified_user_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skip Notification User ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_certificate_generator_skipped_notify_user_count[$__range]))"
    }
   ]
  },
  {
   "title": "Collection Cert Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_certificate_generator_success_events_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_certificate_generator_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_certificate_generator_failed_events_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_certificate_generator_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Collection Cert Generator Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"collection-certificate-generator-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  },
  { "title": "Collection Cert Pre Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_total_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_skipped_event_count[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_failed_events_count[$__range]))"
    }
   ]
  },
  {
   "title": "DB Read ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_db_read_count[$__range]))"
    }
   ]
  },
  {
   "title": "DB Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_db_update_count[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(flink_taskmanager_job_task_operator_collection_cert_pre_processor_cache_hit_cout[$__range]))"
    }
   ]
  },
  {
   "title": "Collection Cert Pre Processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_cert_pre_processor_success_events_count)",
     "legendFormat": "Success Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_cert_pre_processor_skipped_event_count)",
     "legendFormat": "Skipped Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_collection_cert_pre_processor_failed_events_count)",
     "legendFormat": "Failed Events"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_questionset_publish_total_events_count)",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Collection Cert Pre Processor Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"collection-cert-pre-processor-taskmanager-prometheus\" })",
     "legendFormat": "Consumer lag"
    }
   ]
  }
 ]
}