{
 "title": "Lag Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "ntpprod" }
  ]
 },
 "panels": [
  {
   "title": "Logstash Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "logstash Raw events lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.flink.kp.events\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "logstash Telemetry Error events lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.telemetry-log.indexer\", job=\"processing-kafka-exporter\", topic=\"ntpprod.druid.events.error\"})"
      }
     ]
    },
    {
     "title": "logstash Telemetry log events lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.telemetry-log.indexer\", job=\"processing-kafka-exporter\", topic=\"ntpprod.druid.events.log\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "KP Flink Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "AssessmentAggregator Lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"assessment-aggregator-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "ActivityAggUpdater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"activity-aggregate-updater-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "RelationCache Updater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"relation-cache-updater-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "PostPublishProcessor lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"post-publish-processor-taskmanager-prometheus\" })"
      }
     ]
    }
   ]
  },
  {
   "title": "KP Flink Consumer Group Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AssessmentAggregator Lag",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-assessment-aggregator-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "ActivityAggUpdater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-activity-aggregate-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "RelationCache Updater lag",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-relation-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "PostPublishProcessor Lag",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-post-publish-processor-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "KP Samza Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CourseBatchUpdater",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50k\nCritical: 100k",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'course-batch-updater' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CourseCertificateGenerator",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'course-certificate-generator' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PublishPipeline",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50K\nCritical: 100K",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'publish-pipeline' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CompositeSearchIndexer",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50K\nCritical: 100K",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'composite-search-indexer') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AuditHistoryIndexer",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50K\nCritical: 100k",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'audit-history-indexer' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AuditHistoryIndexer",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50K\nCritical: 100K",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'audit-history-indexer' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AuditEventGenerator",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 50K\nCritical: 100K",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'audit-event-generator' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AssetEnrichment",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 50K\nCritical: 100K",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"consumer_lag\") FROM \"pipeline_metrics\" WHERE (\"job_name\" = 'asset-enrichment' ) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DP Flink Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion Router lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 5M\nCritical:  10M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"ingest-router-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "TelemetryExtractor lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 5M\nCritical:  10M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"telemetry-extractor-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "Preprocessor lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"pipeline-preprocessor-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "DruidValidator lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"druid-validator-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "DenormalizationPrimary lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"de-normalization-primary-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "DenormalizationSecondarylag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"de-normalization-secondary-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "Device-Profile-Updater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"device-profile-updater-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "Content-Cache-Updater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"content-cache-updater-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "UserCacheUpdaterV2 lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max { job = \"user-cache-updater-v2-taskmanager-prometheus\" })"
      }
     ]
    },
    {
     "title": "SummaryDenorm lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max{ job = \"summary-denormalization-taskmanager-prometheus\" })"
      }
     ]
    }
   ]
  },
  {
   "title": "DP Flink Consumer Group Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion Router lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 5M\nCritical:  10M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-ingest-router-group\", job=\"ingestion-kafka-exporter\", topic=\"ntpprod.telemetry.ingestion\"})"
      }
     ]
    },
    {
     "title": "Telemetry Extractor lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 5M\nCritical:  10M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-telemetry-extractor-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "PreProcessor lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-pipeline-preprocessor-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DruidValidator lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-druid-validator-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DenormalizationPrimary lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-telemetry-denorm-primary-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DenormalizationSecondary lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-telemetry-denorm-secondary-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DeviceProfileUpdater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-device-profile-updater-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "ContentCacheUpdater lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-content-cache-updater-group\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "UserCacheUpdaterV2 lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-user-cache-updater-consumer-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "SummaryDenorm lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-summmary-denorm-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "Error Denorm lag",
     "type": "singlestat",
     "description": "Threshold:\nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=\"ntpprod-error-denorm-group\", job=\"processing-kafka-exporter\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Secor Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "IngestionTelemetryBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.ingestion.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "RawTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.raw.events.backup\", job=\"processing-kafka-exporter\"}) "
      }
     ]
    },
    {
     "title": "FailedTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.failed.backup\", job=\"processing-kafka-exporter\"}) "
      }
     ]
    },
    {
     "title": "ExtractorDuplicateEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.extractor.duplicate.backup\", job=\"processing-kafka-exporter\"}) "
      }
     ]
    },
    {
     "title": "ChannelTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without (partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.channel.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DerivedUniqueTelemetryBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.derived.unique.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "AssesRawEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without (partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.assess.raw\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "ExtractorFailedEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.extractor.failed.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "UniqueTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.unique.events.backup\", job=\"processing-kafka-exporter\", topic=\"ntpprod.telemetry.unique\"}) "
      }
     ]
    },
    {
     "title": "ChannelEventsSummaryBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.summary.channel.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "LearningFailedEventsBackup",
     "type": "singlestat",
     "description": "Threshod: \nWarning: 50K\nCritical: 1L",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.failed.learning.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DenormTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.denorm.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DeviceProfileEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.events.device.profile.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DuplicateTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.duplicate.backup\", job=\"processing-kafka-exporter\"}) "
      }
     ]
    },
    {
     "title": "AssessTelemetryEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.telemetry.assess.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "DerivedDenormEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 15M\nCritical: 20M",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.summary.backup\", job=\"processing-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "LearningGraphEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 1M\nCritical: 1.5M",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.learning.graph.events.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "CourceBatchEventsBackup",
     "type": "singlestat",
     "description": "Threshold: \nWarning: 4M\nCritical: 8M",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroupzookeeper_lag_zookeeper{consumergroup=~\"$env.coursebatch.job.request.backup\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "WFS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Data Products time taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dataproduct_workflowsummarymodel_time_taken_secs)",
       "legendFormat": "time_taken: {{ subsystem }}"
      }
     ]
    },
    {
     "title": "Total Data Products Input count",
     "type": "table",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_input_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    },
    {
     "title": "Total Data Products Output count",
     "type": "table",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(dataproduct_workflowsummarymodel_output_events[${__range_s}s])) by (report_date)",
       "legendFormat": "input_events"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Rollup Cluster DataSource Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "AuditRollupSyncts",
     "type": "singlestat",
     "description": "Datasource name:  audit-rollup-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"rollup\",exported_job=\"audit-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "ErrorRollupSyncts",
     "type": "singlestat",
     "description": "Datasource name:  error-rollup-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"rollup\",exported_job=\"error-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "SummaryDistinctCounts",
     "type": "singlestat",
     "description": "Datasource name:  summary-distinct-counts",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"rollup\",exported_job=\"summary-distinct-counts\"}"
      }
     ]
    },
    {
     "title": "SummaryRollupSyncts",
     "type": "singlestat",
     "description": "Datasource name:  summary-rollup-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"rollup\",exported_job=\"summary-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryRollupSyncts",
     "type": "singlestat",
     "description": "Datasource name:  summary-rollup-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"rollup\",exported_job=\"telemetry-rollup-syncts\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster DataSource Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary-Events",
     "type": "singlestat",
     "description": "DataSource name: summary-events",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Datasource name: telemetry-events-syncts",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Datasource name:  telemetry-feedback-events",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_ingest_kafka_lag{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Rolllup Cluster Segment Unavailable Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "AuditRollupSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"audit-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "ErrorRollupSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"error-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "SummaryDistinctCounts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"summary-distinct-counts\"}"
      }
     ]
    },
    {
     "title": "SummaryMonthlyRollupSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"summary-monthly-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "SummaryRollupSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"summary-rollup-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryRollupSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"rollup\",exported_job=\"telemetry-rollup-syncts\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Druid Raw Cluster Segment Unavailable Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "ContentModelSnapshot",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"content-model-snapshot\"}"
      }
     ]
    },
    {
     "title": "OfflineDesktopEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"offline-desktop-events\"}"
      }
     ]
    },
    {
     "title": "PipelineMetrics",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"pipeline-metrics\"}"
      }
     ]
    },
    {
     "title": "SummaryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"summary-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryErrorEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-error-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events\"}"
      }
     ]
    },
    {
     "title": "TelemetryEventsSyncts",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-events-syncts\"}"
      }
     ]
    },
    {
     "title": "TelemetryFeedbackEvents",
     "type": "singlestat",
     "description": "Threshold:\nCritical: 1",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "druid_segment_unavailable_count{cluster=\"raw\",exported_job=\"telemetry-feedback-events\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Secor Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "derived-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"derived-telemetry-.+\"})"
      }
     ]
    },
    {
     "title": "derived-denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"derived-denorm-events-.+\"})"
      }
     ]
    },
    {
     "title": "channel-summary-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-summary-.+\"})"
      }
     ]
    },
    {
     "title": "assess-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-events-.+\"})"
      }
     ]
    },
    {
     "title": "assess-raw-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"assess-raw-events-.+\"})"
      }
     ]
    },
    {
     "title": "device-profile-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"device-profile-.+\"})"
      }
     ]
    },
    {
     "title": "learning-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-events-.+\"})"
      }
     ]
    },
    {
     "title": "learning-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"learning-failed-.+\"})"
      }
     ]
    },
    {
     "title": "content-consumption-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"content-consumption-events-.+\"})"
      }
     ]
    },
    {
     "title": "failed-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"failed-telemetry-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-duplicate-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-duplicate-.+\"})"
      }
     ]
    },
    {
     "title": "extractor-failed-backup",
     "type": "singlestat",
     "description": "Expected running process count: 1",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"extractor-failed-.+\"})"
      }
     ]
    },
    {
     "title": "channel-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"channel-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "raw-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"raw-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "ingestion-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 4",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"ingestion-telemetry-backup-.+\"})"
      }
     ]
    },
    {
     "title": "denorm-events-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"denorm-events-backup-.+\"})"
      }
     ]
    },
    {
     "title": "unique-telemetry-backup",
     "type": "singlestat",
     "description": "Expected running process count: 8",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"unique-telemetry-backup-.+\"})"
      }
     ]
    }
   ]
  }
 ]
}