{
 "title": "LP Pipeline Metrics",
 "tags": [ "pipeline" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "ntpprod" }
  ]
 },
 "panels": [
  {
   "title": "Publish Pipeline Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'image-tagging' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'image-tagging' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search indexer Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'image-tagging' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "audit-history-indexer" }
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"error\", \"failed\" FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/ AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "audit-history-indexer" }
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "audit-event-generator" }
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "audit-event-generator" }
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "publish-pipeline" }
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "publish-pipeline" }
     ]
    }
   ]
  },
  {
   "title": "Composite Indexer Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "composite-search-indexer" }
     ]
    }
   ]
  },
  {
   "title": "Composite Indexer Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "query": "SELECT \"error\", \"failed\" FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/ AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "composite-search-indexer" }
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "image-tagging" }
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pipeline_metrics",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "image-tagging" }
     ]
    }
   ]
  }
 ]
}