{
 "title": "LPA Metrics",
 "tags": [ "pipeline" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "ntpprod" }
  ]
 },
 "panels": [
  {
   "title": "Data Products Daily Aggregated Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "analytics_metrics",
     "query": "SELECT sum(\"number_of_output\") AS \"Output\", sum(\"success\") AS \"Success\", sum(\"time_spent\") AS \"Time spent\" FROM \"autogen\".\"analytics_metrics\" WHERE (\"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "number_of_output" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Output" ], "type": "alias" }
      ],
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Success" ], "type": "alias" }
      ],
      [
       { "params": [ "time_spent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Time spent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Products Daily Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "analytics_metrics",
     "query": "SELECT count(\"job_name\") FROM \"autogen\".\"analytics_metrics\" WHERE \"env\" =~ /^$env$/  AND $timeFilter AND success = 1 group by time(1d)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "success" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Products Daily Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ " 1d " ], "type": "time" }
     ],
     "measurement": "analytics_metrics",
     "query": "SELECT count(\"job_name\") FROM \"autogen\".\"analytics_metrics\" WHERE \"env\" =~ /^$env$/  AND $timeFilter AND success = 1 group by time(1d)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "failure" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "is_success", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "# Data Products All jobs Daily Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "analytics_metrics",
     "query": "SELECT \"number_of_input\" AS \"Input\", \"number_of_output\" AS \"Output\", \"success\" AS \"Success\", \"time_spent\" AS \"Time spent\" FROM \"autogen\".\"analytics_metrics\" WHERE (\"env\" =~ /^$env$/) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "number_of_input" ], "type": "field" },
       { "params": [ "Input" ], "type": "alias" }
      ],
      [
       { "params": [ "number_of_output" ], "type": "field" },
       { "params": [ "Output" ], "type": "alias" }
      ],
      [
       { "params": [ "success" ], "type": "field" },
       { "params": [ "Success" ], "type": "alias" }
      ],
      [
       { "params": [ "time_spent" ], "type": "field" },
       { "params": [ "Time spent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "DataExhaust Request Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "analytics_metrics",
     "query": "SELECT \"number_of_input\" AS \"Inputs\", \"number_of_output\" AS \"Outputs\", \"success\" AS \"Success\", \"time_spent\" AS \"TimeSpent\", \"tag\" AS \"ClientKey\" FROM \"autogen\".\"analytics_metrics\" WHERE (\"env\" =~ /^$env$/ AND \"job_name\" = 'DataExhaustJob' AND \"job_id\" <> 'AnalyticsDataPipeline') AND $timeFilter GROUP BY \"job_id\"",
     "select": [
      [
       { "params": [ "number_of_input" ], "type": "field" },
       { "params": [ "Inputs" ], "type": "alias" }
      ],
      [
       { "params": [ "number_of_output" ], "type": "field" },
       { "params": [ "Outputs" ], "type": "alias" }
      ],
      [
       { "params": [ "success" ], "type": "field" },
       { "params": [ "Success" ], "type": "alias" }
      ],
      [
       { "params": [ "time_spent" ], "type": "field" },
       { "params": [ "TimeSpent" ], "type": "alias" }
      ],
      [
       { "params": [ "tag" ], "type": "field" },
       { "params": [ "ClientKey" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "DataExhaustJob" },
      { "condition": "AND", "key": "job_id", "operator": "<>", "value": "AnalyticsDataPipeline" }
     ]
    }
   ]
  }
 ]
}