{
 "title": "NGINX-Comparison",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(nginx_http_requests_total, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Today"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1d))",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1w))",
     "legendFormat": "Same Day Last Week"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"4..|5..\"}[5m])) /sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "Today"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"4..|5..\"}[5m] offset 1d))  / sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1d))) * 100",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"4..|5..\"}[5m] offset 1w))  / sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1w))) * 100",
     "legendFormat": "LastWeek Same Day"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..\"}[5m]))  / sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m]))) * 100",
     "legendFormat": "Today"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..\"}[5m] offset 1d))  / sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1d))) * 100",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$cluster\", status!~\"2..|3..\"}[5m] offset 1w))  / sum(increase(nginx_http_requests_total{cluster=~\"$cluster\"}[5m] offset 1w))) * 100",
     "legendFormat": "LastWeek Same Day"
    }
   ]
  }
 ]
}