{
 "title": "Nginx",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "swarm",
    "query": "label_values(nginx_http_requests_total, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{cluster=~\"$swarm\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$swarm\", status_code!~\"4..|5..\"}[5m])) by (status_code) / ignoring(status_code) group_left sum(increase(nginx_http_requests_total{cluster=~\"$swarm\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{cluster=~\"$swarm\", status_code!~\"2..|3..\"}[5m])) by (status_code) / ignoring(status_code) group_left sum(increase(nginx_http_requests_total{cluster=~\"$swarm\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}