{
 "title": "NOC Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "swarm",
    "query": "label_values(node_load1,cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Publish Pipeline Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'image-tagging' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Publish Pipeline Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composite search index Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'composite-search-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit History Indexer Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'audit-history-indexer' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image Tagging Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'image-tagging' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Event Generator Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SELECT sum(\"success\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^$env$/  AND \"job_name\" = 'publish-pipeline' AND $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"failed\") FROM \"pipeline_metrics\" WHERE \"env\" =~ /^ntpprod$/  AND \"job_name\" = 'audit-event-generator' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_request_status_count{cluster=~\"$swarm\", status_code!~\"2..|3..|5..\"}[5m])) by (status_code) / ignoring(status_code) group_left sum(increase(nginx_request_status_count{cluster=~\"$swarm\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_request_status_count{cluster=~\"$swarm\", status_code!~\"2..|3..|4..\"}[5m])) by (status_code) / ignoring(status_code) group_left sum(increase(nginx_request_status_count{cluster=~\"$swarm\"}[5m]))) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Disk utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{ mountpoint=\"/\", job=\"vm-node-exporter\"} - node_filesystem_free_bytes{ mountpoint=\"/\"}) * 100\n/ \nnode_filesystem_size_bytes{mountpoint=\"/\"}  * on (instance) group_left(nodename) node_uname_info )\nby (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Load avg on VM's",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=\"vm-node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}