{
 "title": "Open Policy Agent Metrics",
 "description": "Open Policy Agents Runtime metrics",
 "tags": [
  "go",
  "golang",
  "opa"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines{namespace=\"$namespace\",  endpoint=\"opa-metrics\"}, job)"
   },
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (job) / sum(rate(http_request_duration_seconds_count{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
     "legendFormat": "50th Quantile (Median) - {{job}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
     "legendFormat": "90th Quantile - {{job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
     "legendFormat": "95th Quantile - {{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
     "legendFormat": "99th Quantile - {{job}}"
    }
   ]
  },
  {
   "title": "Object and Pointers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_frees_total{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences per $interval",
     "type": "graph",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated Per $interval",
     "type": "graph",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation per $interval",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - stack allocator"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - system stack allocator"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory In Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes allocated & still in-use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes waiting to be used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes in use ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes released to OS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Objects allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Off-heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Runtime Memory Info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mspan"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mspan system"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mcache"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mcache system"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - profiling bucket hash table"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - garbage collection system metadata"
      },
      {
       "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - other system allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - next garbage collection"
      }
     ]
    },
    {
     "title": "Mspan bytes usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for mspan obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for mcache obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes in use by mcache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for garbage collection system metadata",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used by the profiling bucket hash table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes when next garbage collection will take place",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for other system allocations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - bytes of memory are used for other runtime allocations"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - quantile {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}