{
 "title": "Process Exporter",
 "description": "Process metrics",
 "tags": [ "OS" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total{job=\"process-exporter\"},instance)"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\"}, groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\", instance=\"$instance\"}[$interval])) by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "active memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\", instance=\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual / page memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\", instance=\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "num processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_procs{groupname=~\"$processes\", instance=\"$instance\"}) by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}