{
 "title": "Availability",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"availability.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe HTTP status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}