@Library('deploy-conf') _
node() {
    try {
        String ANSI_GREEN = "\u001B[32m"
        String ANSI_NORMAL = "\u001B[0m"
        String ANSI_BOLD = "\u001B[1m"
        String ANSI_RED = "\u001B[31m"
        String ANSI_YELLOW = "\u001B[33m"

        stage('checkout public repo') {
            cleanWs()
            checkout scm
        }

            ansiColor('xterm') {
                values = lp_dp_params()
                values.put('module', 'Core')
                stage('get artifact') {
                    currentWs = sh(returnStdout: true, script: 'pwd').trim()
                    artifact = values.artifact_name + ":" + values.artifact_version
                    commit_hash = values.artifact_version.split('_')[1]
                    values.put('currentWs', currentWs)
                    if (params.artifact_source == "ArtifactRepo") {
                        println(ANSI_BOLD + ANSI_YELLOW + '''\
                        Option chosen is ArtifactRepo, ignoring any previously copied artifacts and new artifacts will be downloaded from remote source
                        '''.stripIndent().replace("\n", " ") + ANSI_NORMAL)
                        ansiblePlaybook = "${currentWs}/ansible/artifacts-download.yml"
                        ansibleExtraArgs = """\
                               --extra-vars "artifact=${artifact}
                               artifact_path=${currentWs}/${artifact}"
                               --vault-password-file /var/lib/jenkins/secrets/vault-pass
                               """.stripIndent().replace("\n", " ")
                        values.put('ansiblePlaybook', ansiblePlaybook)
                        values.put('ansibleExtraArgs', ansibleExtraArgs)
                        ansible_playbook_run(values)
                    }
                    else{
                        println(ANSI_BOLD + ANSI_YELLOW + '''\
                    Option chosen is JenkinsJob, using the artifacts copied 
                    '''.stripIndent().replace("\n", " ") + ANSI_NORMAL)
                    }
                }
                stage('deploy artifact'){
                    sh """
                      unzip ${artifact}
                      unzip -o content-editor.zip -d content-editor
                      export editor_version_number=${values.artifact_version}
                      export build_number=${commit_hash}
                      sed -i -e 's/dispatcher:\"console\"/dispatcher:\"piwik\"/g' content-editor/scripts/*
                      sed -i 's:/api:/action:g' content-editor/scripts/base-editor.min.js
                      sed -i 's/useProxyForURL:true/useProxyForURL:false/g' content-editor/scripts/base-editor.min.js
                      sed -i -e 's/dispatcher:\"local\"/dispatcher:\"piwik\"/g' content-editor/scripts/*
                      mv content-editor ansible
                    """
                      
                      ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                      ansibleExtraArgs = "--tags content-editor --extra-vars \"folder_name=content-editor source_name=${currentWs}/ansible/content-editor\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                      values.put('ansiblePlaybook', ansiblePlaybook)
                      values.put('ansibleExtraArgs', ansibleExtraArgs)
                      println values
                      ansible_playbook_run(values)
                        
                    sh """                                                   
                      zip -r content-editor-artifact.zip ansible/content-editor
                      cd ansible/content-editor
                      npm install
                      npm install promise
                      gulp minifyJs
                      gulp copystyleImages
                      gulp clean
                      gulp injectrenamedfiles
                      gulp package
                    """
                        
                      ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                      ansibleExtraArgs = "--tags editor --extra-vars \"folder_name=artefacts/editor source_name=${currentWs}/ansible/content-editor/dist/editor\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                      values.put('ansiblePlaybook', ansiblePlaybook)
                      values.put('ansibleExtraArgs', ansibleExtraArgs)
                      println values
                      ansible_playbook_run(values)  
                      
                      ansiblePlaybook = "${currentWs}/ansible/deploy-plugins.yml"
                      ansibleExtraArgs = "--tags core-plugins --extra-vars \"folder_name=artefacts/coreplugins source_name=${currentWs}/ansible/content-editor/dist/coreplugins\" --vault-password-file /var/lib/jenkins/secrets/vault-pass"  
                      values.put('ansiblePlaybook', ansiblePlaybook)
                      values.put('ansibleExtraArgs', ansibleExtraArgs)
                      println values
                      ansible_playbook_run(values)
                        
                    sh """  
                      rm -rf node_modules
                      cd ..
                      zip -r content-editor.zip ${currentWs}/ansible/content-editor
                    """
                        
                    archiveArtifacts artifacts: "${artifact}", fingerprint: true, onlyIfSuccessful: true
                    archiveArtifacts artifacts: 'metadata.json', onlyIfSuccessful: true
                    currentBuild.description = "ArtifactVersion: ${values.artifact}, PrivateRepo: ${params.private_branch}, BranchOrTag: ${params.branch_or_tag}"
                }
            }
        }
    catch (err) {
        throw err
    }
}
