#!groovy

node('docker') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }
       stage('Pre-Build'){

         sh('./ansible/installDeps.sh')

       }

       stage('Build'){

          ansible-playbook -i ansible/inventory/admin ansible/bootstrap.yml --tags "hosts=dev-cassandra"
       }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
