#!groovy

node('docker') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }



       stage('Pre-Build'){
         sh('chmod a+x ansible/installDeps.sh')
         sh('./ansible/installDeps.sh')
       }

       stage('Build'){

        sh('ansible-playbook -i ansible/inventory/admin ansible/bootstrap.yml --extra-vars "hosts=dev-cassandra"')
       }

    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
