#!groovy

node('general-dev') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }

       stage('Pre-Build'){

         sh('./images/kong/installDeps.sh')

       }

       stage('Build'){

         env.NODE_ENV = "build"

         print "Environment will be : ${env.NODE_ENV}"
         sh('./images/kong/build.sh')

       }

       stage('Publish'){

         echo 'Push to Repo'
         sh 'ls -al ~/'
         sh 'ARTIFACT_LABEL=bronze ./images/kong/dockerPushToRepo.sh'

       }

       stage('Deploy to Dev'){

         sh './images/kong/metadata.sh > metadata.json'
         sh 'METADATA_FILE=metadata.json ARTIFACT_LABEL=bronze ENV=dev ./images/kong/deploy.sh'
         sh 'cat metadata.json'
         archive includes: "metadata.json"

       }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
