#!groovy

node('general-dev') {

    currentBuild.result = "SUCCESS"

    try {

       stage('Checkout'){

          checkout scm
       }

       stage('Pre-Build'){

         sh('./images/logger/installDeps.sh')

       }

       stage('Build'){

         env.NODE_ENV = "build"

         print "Environment will be : ${env.NODE_ENV}"
         sh('./images/kibana/build.sh')
         sh('./images/logstash/build.sh')

       }

       stage('Publish'){

         echo 'Push to Repo'
         sh 'ls -al ~/'
         sh 'ARTIFACT_LABEL=bronze ./images/kibana/dockerPushToRepo.sh'
         sh 'ARTIFACT_LABEL=bronze ./images/logstash/dockerPushToRepo.sh'

       }

       stage('Deploy to Dev'){

         sh 'ARTIFACT_LABEL=bronze ENV=dev ./images/logger/deploy.sh'

       }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
