pipeline {
    agent {
        label 'kong-api'
    }
    stages {
        stage('Deploy') {
            steps {
                sh '''
                export ANSIBLE_HOST_KEY_CHECKING=False
                cd ansible
                ansible-playbook -i inventory/dev api-manager.yml --tags kong-api --vault-password-file /run/secrets/vault-pass
                '''
            }
        }
    }
}